#!/bin/bash -e

source ~/Scripts/common.sh

_self=$(realpath $_rootdir/functions)
_dir=$(dirname $_self)
_pass=$(cat $(echo ${_rootdir}/.pass))

__text() { echo -e "\e[0m${1}"; }
__er()   { echo -e "\e[0;31m${1}\e[0m"; __exit "${2}"; }
__inf()  { echo -e "\e[0;32m${1}\e[0m"; }
__warn() { echo -e "\e[0;33m${1}\e[0m"; }
__exit() { echo -e "\n\t\e[1m${1}\e[0m\n"; }

__setup()
{
    if [[ $_pass == "" ]]; then
        __er "Put your password into ${_dir}/.pass"
    else
        __aptInstall       \
            gnome-terminal \
            pip            \
            highlight      \
            elinks
        __pipInstall \
            pygments
    fi
}

__getDir(){ echo $(dirname $(realpath $1)); }
__getPass(){ cat $(echo ${_rootdir}/.pass); }
__sudoExec(){ eval "echo '$(__getPass)' | sudo -S $@"; }
__sudoExecH(){ eval "echo '$(__getPass)' | sudo -SH $@"; }
__cat(){ pygmentize -g $@; }
__highlight(){ highlight -O ansi $@; }
__execString(){ eval $1; }

__catExt()
{
    {
        pygmentize ${1}
    } || {
        cat ${1}
    }
    
}

__aptInstall()
{
    toInstall=()
    for i in $@; do
        if [ $(__isCommandMissing $1) -eq 1 ]; then
            toInstall=( $toInstall $i )
        fi
    done

    if ! [ ${#toInstall} -eq 0 ]; then
        __inf "Installing [$toInstall]...\n"
        __sudoExec "apt-get install -y $toInstall"
    fi
}

__pipInstall()
{
    __sudoExecH "pip install --upgrade pip 2>/dev/null 1>/dev/null"
    #__sudoExec "pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U"

    cmds=()
    for i in $@; do
        if [[ $(echo $(__sudoExecH "pip list | grep -i $i 2>/dev/null")) == "" ]]; then
            cmds=( $cmds $i )
        fi
    done

    if ! [ ${#cmds} -eq 0 ]; then
        __inf "Installing [$cmds]...\n"
        __sudoExecH "pip install $cmds"
    fi
}

__isCommandMissing()
{
    if [[ $(which $1 2>/dev/null) == "$1 not found" ]]; then echo 1; else echo 0; fi
}

__removeExistingCommands()
{
    cmds=()
    for i in $@; do
        if [ $(__isCommandMissing $1) -eq 1 ]; then
            cmds=( $cmds $i )
        fi
    done
    echo $cmds
}

export __html_c=0
__html()
{
    setup=$(__setup)
    if [[ $setup != "" ]]; then
        __warn "Can't render html without elinks; Please install it!"
    fi
    for i in $@; do
        if [[ $setup != "" ]]; then
            __text $i
        else
            filename=/tmp/$(date +%Y%m%d%H%M%S)_${__html_c}.html
            echo $i > $filename
            elinks -dump -dump-color-mode 1 $filename
            rm $filename
            export __html_c=$(( __html_c + 1 ))
        fi
    done
}

##
# @param title
# @param geometry
# @param any...
__term()
{
    geometry=$(if [[ $1 == "" ]]; then echo ""; else echo "--geometry=$1"; fi)
    $(which gnome-terminal) $geometry $@
}


