#!/bin/bash

__text() { echo -e "\e[0m${1}"; }
__er()   { echo -e "\e[0;31m${1}\e[0m"; __exit "${2}"; }
__inf()  { echo -e "\e[0;32m${1}\e[0m"; }
__warn() { echo -e "\e[0;33m${1}\e[0m"; }
__exit() { echo -e "\n\t\e[1m${1}\e[0m\n"; }

__setup()
{
    ##
    # install elinks
    if [[ $(which elinks 2>/dev/null) == "elinks not found" ]]; then
        __er "Please install elinks, ex:" "sudo apt-get install -y elinks"
    fi
    
    ##
    # install vimcat
    if [[ $(which vimcat 2>/dev/null) == "vimcat not found" ]]; then
        __inf "Installing vimpager...\n"
        git clone https://github.com/rkitover/vimpager.git /tmp/vimpager 2>/dev/null
        cd /tmp/vimpager/
        sudo make install-deb
        sudo make install
    fi
}

export __html_c=0
__html()
{
    setup=$(__setup)
    if [[ $setup != "" ]]; then
        __warn "Can't render html without elinks; Please install it!"
    fi
    for i in $@; do
        if [[ $setup != "" ]]; then
            __text $i
        else
            filename=/tmp/$(date +%Y%m%d%H%M%S)_${__html_c}.html
            echo $i > $filename
            elinks -dump -dump-color-mode 1 $filename
            rm $filename
            export __html_c=$(( __html_c + 1 ))
        fi
    done
}

##
# @param title
# @param geometry
# @param any...
__term()
{
    #title=$(if [[ $1 == "" ]]; then echo ""; else echo "--title=$1"; fi)
    geometry=$(if [[ $2 == "" ]]; then echo ""; else echo "--geometry=$2"; fi)

    $(which gnome-terminal) $geometry $@
}

__execString()
{
    toExec=$1; __inf "Executing: $toExec"; $toExec
}
