#!/bin/bash

_self=$(realpath $0)
_dir=$(dirname $_self)
_include_functions=$(echo ${_dir}/functions)
_pass=$(cat $(echo ${_dir}/.pass))

source $_include_functions

__gul=133x32+0+0
__gur=133x32+674+0
__gbl=133x32+0-0
__gbr=133x32+674-0

_dirMonitors=$(echo ${_dir}/.open-monitors)
__pgMonitor=$(echo $_dirMonitors/__pgMonitor)
__htopMonitor=$(echo $_dirMonitors/__htopMonitor)

mkdir $_dirMonitors 2>/dev/null
touch ${__pgMonitor} 2>/dev/null; chmod +x ${__pgMonitor}
touch ${__htopMonitor} 2>/dev/null; chmod +x ${__htopMonitor}

cat <<EOF > $__pgMonitor
#!/bin/bash
echo '''$_pass''' | sudo -S clear
sudo tail -f /var/log/postgresql/postgresql-9.5-main.log
EOF

cat <<EOF > $__htopMonitor
#!/bin/bash
echo '''$_pass''' | sudo -S clear
sudo htop
EOF

__execString "__term '' $__gul --command '$__pgMonitor' &"
__execString "__term '' $__gbl --command '$__htopMonitor' &"

