#!/bin/bash -e

source ~/Scripts/common.sh

_self=$(realpath $_rootdir/update-system)
_dir=$(dirname $_self)
_term=$(which gnome-terminal)

source ${_rootdir}/functions

if [[ $1 == "go" ]]; then
    __inf "\nRunning updates"
    echo "$(__getPass)" | sudo -S clear
    sudo aptitude update
    sudo aptitude full-upgrade -y
    sudo aptitude autoclean
    __inf "Done!"
    sleep 5
else
    gnome-terminal --command "${_self} go"
fi
